learn_rails/config/routes.rb
Rails.application.routes.draw do
  resources :members
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

learn_rails/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

learn_rails/app/models/member.rb
class Member < ApplicationRecord
end

learn_rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

learn_rails/app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]

  # GET /members
  # GET /members.json
  def index
    @members = Member.all
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def member_params
      params.require(:member).permit(:name, :age, :phone)
    end
end

learn_rails/app/helpers/application_helper.rb
module ApplicationHelper
end

learn_rails/app/helpers/members_helper.rb
module MembersHelper
end

learn_rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LearnRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

learn_rails/app/views/members/_form.html.erb
<%= form_with(model: member, local: true) do |form| %>
  <% if member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
        <% member.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

learn_rails/app/views/members/edit.html.erb
<h1>Editing Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

learn_rails/app/views/members/index.html.erb
<p id="notice"><%= notice %></p>

<h1>First Database</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= member.name %></td>
        <td><%= member.age %></td>
        <td><%= member.phone %></td>
        <td><%= link_to 'Show', member %></td>
        <td><%= link_to 'Edit', edit_member_path(member) %></td>
        <td><%= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Member', new_member_path %>

learn_rails/app/views/members/new.html.erb
<h1>New Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Back', members_path %>

learn_rails/app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @member.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @member.age %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @member.phone %>
</p>

<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>